/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;

import java.util.List;
import javax.swing.ImageIcon;
import modelo.Equipe;

/**
 *
 * @author nickb
 */
public class frmCampeonato extends javax.swing.JDialog {

    /**
     * Creates new form frmCampeonato
     */
    List<Equipe> lista;
    int trofeu;
    ImageIcon nullIcon = new ImageIcon("src\\imagens\\logos\\Null.png");
    
    public frmCampeonato(java.awt.Frame parent, boolean modal, List<Equipe> lista, int trofeu) {
        super(parent, modal);
        this.lista = lista;
        this.trofeu = trofeu;
        initComponents();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnQ11 = new javax.swing.JButton();
        btnQ22 = new javax.swing.JButton();
        btnQ21 = new javax.swing.JButton();
        btnS12 = new javax.swing.JButton();
        btnQ31 = new javax.swing.JButton();
        btnQ32 = new javax.swing.JButton();
        btnQ41 = new javax.swing.JButton();
        btnQ42 = new javax.swing.JButton();
        btnQ12 = new javax.swing.JButton();
        btnS21 = new javax.swing.JButton();
        btnS22 = new javax.swing.JButton();
        btnS11 = new javax.swing.JButton();
        btnF1 = new javax.swing.JButton();
        btnF2 = new javax.swing.JButton();
        btnCampeao = new javax.swing.JButton();
        lblBRTS = new javax.swing.JLabel();
        lblTrofeu = new javax.swing.JLabel();
        lblMensagem = new javax.swing.JLabel();
        lblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Simulação do Campeonato");
        setBackground(new java.awt.Color(255, 255, 153));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnQ11.setBackground(new java.awt.Color(0, 0, 0));
        btnQ11.setIcon(lista.get(0).getLogo());
        btnQ11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnQ11.setContentAreaFilled(false);
        btnQ11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQ11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQ11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQ11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        btnQ22.setBackground(new java.awt.Color(0, 0, 0));
        btnQ22.setIcon(lista.get(3).getLogo());
        btnQ22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnQ22.setContentAreaFilled(false);
        btnQ22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQ22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQ22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQ22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ22ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));

        btnQ21.setBackground(new java.awt.Color(0, 0, 0));
        btnQ21.setIcon(lista.get(2).getLogo());
        btnQ21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnQ21.setContentAreaFilled(false);
        btnQ21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQ21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQ21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQ21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ21ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        btnS12.setBackground(new java.awt.Color(0, 0, 0));
        btnS12.setIcon(nullIcon);
        btnS12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnS12.setContentAreaFilled(false);
        btnS12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnS12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnS12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnS12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS12ActionPerformed(evt);
            }
        });
        getContentPane().add(btnS12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, -1, -1));

        btnQ31.setBackground(new java.awt.Color(0, 0, 0));
        btnQ31.setIcon(lista.get(4).getLogo());
        btnQ31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnQ31.setContentAreaFilled(false);
        btnQ31.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQ31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQ31.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQ31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ31ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ31, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 100, -1, -1));

        btnQ32.setBackground(new java.awt.Color(0, 0, 0));
        btnQ32.setIcon(lista.get(5).getLogo());
        btnQ32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnQ32.setContentAreaFilled(false);
        btnQ32.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQ32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQ32.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQ32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ32ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ32, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 210, -1, -1));

        btnQ41.setBackground(new java.awt.Color(0, 0, 0));
        btnQ41.setIcon(lista.get(6).getLogo());
        btnQ41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnQ41.setContentAreaFilled(false);
        btnQ41.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQ41.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQ41.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQ41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ41ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ41, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, -1, -1));

        btnQ42.setBackground(new java.awt.Color(0, 0, 0));
        btnQ42.setIcon(lista.get(7).getLogo());
        btnQ42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnQ42.setContentAreaFilled(false);
        btnQ42.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQ42.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQ42.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQ42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ42ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ42, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 480, -1, -1));

        btnQ12.setBackground(new java.awt.Color(0, 0, 0));
        btnQ12.setIcon(lista.get(1).getLogo());
        btnQ12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnQ12.setContentAreaFilled(false);
        btnQ12.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnQ12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnQ12.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnQ12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQ12ActionPerformed(evt);
            }
        });
        getContentPane().add(btnQ12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        btnS21.setBackground(new java.awt.Color(0, 0, 0));
        btnS21.setIcon(nullIcon);
        btnS21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnS21.setContentAreaFilled(false);
        btnS21.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnS21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnS21.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnS21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS21ActionPerformed(evt);
            }
        });
        getContentPane().add(btnS21, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        btnS22.setBackground(new java.awt.Color(0, 0, 0));
        btnS22.setIcon(nullIcon);
        btnS22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnS22.setContentAreaFilled(false);
        btnS22.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnS22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnS22.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnS22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS22ActionPerformed(evt);
            }
        });
        getContentPane().add(btnS22, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 430, -1, -1));

        btnS11.setBackground(new java.awt.Color(0, 0, 0));
        btnS11.setIcon(nullIcon);
        btnS11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnS11.setContentAreaFilled(false);
        btnS11.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnS11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnS11.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnS11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnS11ActionPerformed(evt);
            }
        });
        getContentPane().add(btnS11, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, -1, -1));

        btnF1.setBackground(new java.awt.Color(0, 0, 0));
        btnF1.setIcon(nullIcon);
        btnF1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnF1.setContentAreaFilled(false);
        btnF1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnF1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnF1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, -1, -1));

        btnF2.setBackground(new java.awt.Color(0, 0, 0));
        btnF2.setIcon(nullIcon);
        btnF2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnF2.setContentAreaFilled(false);
        btnF2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnF2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnF2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnF2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnF2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, -1, -1));

        btnCampeao.setBackground(new java.awt.Color(0, 0, 0));
        btnCampeao.setIcon(nullIcon);
        btnCampeao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnCampeao.setContentAreaFilled(false);
        btnCampeao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCampeao.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCampeao.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        getContentPane().add(btnCampeao, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, -1, -1));

        lblBRTS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logos/brts.png"))); // NOI18N
        getContentPane().add(lblBRTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 50, 50));
        getContentPane().add(lblTrofeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 150, 150));

        lblMensagem.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        lblMensagem.setForeground(new java.awt.Color(255, 255, 255));
        lblMensagem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(lblMensagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 900, 50));

        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back-torneio.png"))); // NOI18N
        lblWallpaper.setText("jLabel2");
        getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnQ11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ11ActionPerformed
        btnS11.setIcon(btnQ11.getIcon());
        
        btnQ11.setEnabled(false);
        btnQ12.setEnabled(false);
    }//GEN-LAST:event_btnQ11ActionPerformed

    private void btnF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF2ActionPerformed
        if(!btnF1.getIcon().toString().equals(nullIcon.toString()) && !btnF2.getIcon().toString().equals(nullIcon.toString()))
        {
            btnCampeao.setIcon(btnF2.getIcon());
            
            btnF1.setEnabled(false);
            btnF2.setEnabled(false);
            
            switch (trofeu) {
                case 0 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuEditor.png"));
                case 1 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuBrasil.png"));
                case 2 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuEuropa.png"));
                case 3 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuAmerica.png"));
                case 4 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuAsia.png"));
                case 5 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuUK.png"));
                case 6 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuMundo.png"));
                default -> throw new AssertionError();
            }
            
            for(int i = 0 ; i < lista.size() ; i++)
            {
                if(btnF2.getIcon().equals(lista.get(i).getLogo()))
                {
                    lblMensagem.setText("PARABÉNS, " + lista.get(i).getNome().toUpperCase() + "!!");
                }
            }
            javax.swing.JButton btnFinalizar = new javax.swing.JButton();
            btnFinalizar.setBackground(new java.awt.Color(255, 255, 255));
            btnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
            btnFinalizar.setText("FINALIZAR");
            btnFinalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
            getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 170, -1));
            btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
            });
        }
    }//GEN-LAST:event_btnF2ActionPerformed

    private void btnQ22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ22ActionPerformed
        btnS12.setIcon(btnQ22.getIcon());
        
        btnQ21.setEnabled(false);
        btnQ22.setEnabled(false);
    }//GEN-LAST:event_btnQ22ActionPerformed

    private void btnQ21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ21ActionPerformed
        btnS12.setIcon(btnQ21.getIcon());
        
        btnQ21.setEnabled(false);
        btnQ22.setEnabled(false);
    }//GEN-LAST:event_btnQ21ActionPerformed

    private void btnS12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS12ActionPerformed
        if(!btnS11.getIcon().toString().equals(nullIcon.toString()) && !btnS12.getIcon().toString().equals(nullIcon.toString()))
        {
            btnF1.setIcon(btnS12.getIcon());
        
            btnS11.setEnabled(false);
            btnS12.setEnabled(false);
        }
    }//GEN-LAST:event_btnS12ActionPerformed

    private void btnQ12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ12ActionPerformed
        btnS11.setIcon(btnQ12.getIcon());
        
        btnQ11.setEnabled(false);
        btnQ12.setEnabled(false);
    }//GEN-LAST:event_btnQ12ActionPerformed

    private void btnQ31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ31ActionPerformed
        btnS21.setIcon(btnQ31.getIcon());
        
        btnQ31.setEnabled(false);
        btnQ32.setEnabled(false);
    }//GEN-LAST:event_btnQ31ActionPerformed

    private void btnQ32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ32ActionPerformed
        btnS21.setIcon(btnQ32.getIcon());
        
        btnQ31.setEnabled(false);
        btnQ32.setEnabled(false);
    }//GEN-LAST:event_btnQ32ActionPerformed

    private void btnQ41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ41ActionPerformed
        btnS22.setIcon(btnQ41.getIcon());
        
        btnQ41.setEnabled(false);
        btnQ42.setEnabled(false);
    }//GEN-LAST:event_btnQ41ActionPerformed

    private void btnQ42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQ42ActionPerformed
        btnS22.setIcon(btnQ42.getIcon());
        
        btnQ41.setEnabled(false);
        btnQ42.setEnabled(false);
    }//GEN-LAST:event_btnQ42ActionPerformed

    private void btnS11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS11ActionPerformed
        if(!btnS11.getIcon().toString().equals(nullIcon.toString()) && !btnS12.getIcon().toString().equals(nullIcon.toString()))
        {
            btnF1.setIcon(btnS11.getIcon());
        
            btnS11.setEnabled(false);
            btnS12.setEnabled(false);
        }
    }//GEN-LAST:event_btnS11ActionPerformed

    private void btnS21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS21ActionPerformed
        if(!btnS21.getIcon().toString().equals(nullIcon.toString()) && !btnS22.getIcon().toString().equals(nullIcon.toString()))
        {
            btnF2.setIcon(btnS21.getIcon());

            btnS21.setEnabled(false);
            btnS22.setEnabled(false);
        }
    }//GEN-LAST:event_btnS21ActionPerformed

    private void btnS22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnS22ActionPerformed
        if(!btnS21.getIcon().toString().equals(nullIcon.toString()) && !btnS22.getIcon().toString().equals(nullIcon.toString()))
        {
            btnF2.setIcon(btnS22.getIcon());

            btnS21.setEnabled(false);
            btnS22.setEnabled(false);
        }
    }//GEN-LAST:event_btnS22ActionPerformed

    private void btnF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnF1ActionPerformed
        if(!btnF1.getIcon().toString().equals(nullIcon.toString()) && !btnF2.getIcon().toString().equals(nullIcon.toString()))
        {
            btnCampeao.setIcon(btnF1.getIcon());
            
            btnF1.setEnabled(false);
            btnF2.setEnabled(false);
            
            switch (trofeu) {
                case 0 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuEditor.png"));
                case 1 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuBrasil.png"));
                case 2 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuEuropa.png"));
                case 3 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuAmerica.png"));
                case 4 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuAsia.png"));
                case 5 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuUK.png"));
                case 6 -> lblTrofeu.setIcon(new ImageIcon("src\\imagens\\trofeu\\trofeuMundo.png"));
                default -> throw new AssertionError();
            }
            
            javax.swing.JButton btnFinalizar = new javax.swing.JButton();
            btnFinalizar.setBackground(new java.awt.Color(255, 255, 255));
            btnFinalizar.setForeground(new java.awt.Color(0, 0, 0));
            btnFinalizar.setText("FINALIZAR");
            btnFinalizar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
            getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 170, -1));
            btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
            });
            for(int i = 0 ; i < lista.size() ; i++)
            {
               if(btnF1.getIcon().equals(lista.get(i).getLogo()))
               {
                   lblMensagem.setText("PARABÉNS, " + lista.get(i).getNome().toUpperCase() + "!!");
               }
            }
        }
    }//GEN-LAST:event_btnF1ActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {                                         
         dispose();
    }     
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCampeonato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCampeonato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCampeonato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCampeonato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmCampeonato dialog = new frmCampeonato(new javax.swing.JFrame(), true, null, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCampeao;
    private javax.swing.JButton btnF1;
    private javax.swing.JButton btnF2;
    private javax.swing.JButton btnQ11;
    private javax.swing.JButton btnQ12;
    private javax.swing.JButton btnQ21;
    private javax.swing.JButton btnQ22;
    private javax.swing.JButton btnQ31;
    private javax.swing.JButton btnQ32;
    private javax.swing.JButton btnQ41;
    private javax.swing.JButton btnQ42;
    private javax.swing.JButton btnS11;
    private javax.swing.JButton btnS12;
    private javax.swing.JButton btnS21;
    private javax.swing.JButton btnS22;
    private javax.swing.JLabel lblBRTS;
    private javax.swing.JLabel lblMensagem;
    private javax.swing.JLabel lblTrofeu;
    private javax.swing.JLabel lblWallpaper;
    // End of variables declaration//GEN-END:variables
}
