/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package apresentacao;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.border.LineBorder;
import modelo.Equipe;
import modelo.ListaEquipe;


/**
 *
 * @author nickb
 */
public class frmEquipes extends javax.swing.JDialog {

    /**
     * Creates new form frmTimes
     */
    public frmEquipes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setResizable(false);
    }
    
    int limite = 0;
    int trofeu = 0;
    int liga = 0;
    List<Equipe> lista = new ArrayList<>();
    
    private void atualizarContador()
    {
        lblLimite.setText("Times selecionados: " + limite);
    }
    
    private void atualizarTrofeu()
    {
        lblTrofeu.setIcon(ListaEquipe.listaTrofeu().get(trofeu).getLogo());
    }
    
    private void botao(JToggleButton botao)
    {
        if(botao.isSelected())
        {
            if(limite == 8)
            {
                JOptionPane.showMessageDialog(null, "Só são permitidos 8 clubes.");
                botao.setSelected(false);
            }
            else
            {   
                limite += 1;
                atualizarContador();
                botao.setBorder(new LineBorder(Color.RED, 7));
                
                for(int i = 0 ; i < ListaEquipe.listaEquipe().size() ; i++)
                {
                    if(botao.getIcon().toString().equals(ListaEquipe.listaEquipe().get(i).getLogo().toString()))
                    {
                        lista.add(ListaEquipe.listaEquipe().get(i));
                        lblEquipe.setText(ListaEquipe.listaEquipe().get(i).getNome().toUpperCase());
                    }
                }
            }
        }
        else
        {
            limite -= 1;
            atualizarContador();
            botao.setBorder(null);
            for(int i = 0 ; i < lista.size() ; i++)
            {
                if(botao.getIcon().toString().equals(lista.get(i).getLogo().toString()))
                {
                    lista.remove(i);
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAnteriorLiga = new javax.swing.JButton();
        btnProximoLiga = new javax.swing.JButton();
        lblNomeLiga = new javax.swing.JLabel();
        lblLiga = new javax.swing.JLabel();
        panFundoLiga = new javax.swing.JPanel();
        cbxChave = new javax.swing.JComboBox<>();
        lblEquipe = new javax.swing.JLabel();
        lblLimite = new javax.swing.JLabel();
        btnAnteriorTrofeu = new javax.swing.JButton();
        btnProximoTrofeu = new javax.swing.JButton();
        lblTrofeu = new javax.swing.JLabel();
        panFundoTrofeu = new javax.swing.JPanel();
        btnAleatorio = new javax.swing.JButton();
        btnCriar = new javax.swing.JButton();
        tbpChefe = new javax.swing.JTabbedPane();
        tbpBrasil = new javax.swing.JPanel();
        btnAthleticoPR = new javax.swing.JToggleButton();
        btnAtleticoMG = new javax.swing.JToggleButton();
        btnBahia = new javax.swing.JToggleButton();
        btnBotafogo = new javax.swing.JToggleButton();
        btnCeara = new javax.swing.JToggleButton();
        btnCorinthians = new javax.swing.JToggleButton();
        btnCoritiba = new javax.swing.JToggleButton();
        btnCruzeiro = new javax.swing.JToggleButton();
        btnFlamengo = new javax.swing.JToggleButton();
        btnFluminense = new javax.swing.JToggleButton();
        btnFortaleza = new javax.swing.JToggleButton();
        btnCuiaba = new javax.swing.JToggleButton();
        btnGremio = new javax.swing.JToggleButton();
        btnInternacional = new javax.swing.JToggleButton();
        btnPalmeiras = new javax.swing.JToggleButton();
        btnPaysandu = new javax.swing.JToggleButton();
        btnRemo = new javax.swing.JToggleButton();
        btnSantos = new javax.swing.JToggleButton();
        btnSaoPaulo = new javax.swing.JToggleButton();
        btnVasco = new javax.swing.JToggleButton();
        tbpEuropa = new javax.swing.JPanel();
        btnArsenal = new javax.swing.JToggleButton();
        btnAtleti = new javax.swing.JToggleButton();
        btnBarcelona = new javax.swing.JToggleButton();
        btnLeverkusen = new javax.swing.JToggleButton();
        btnBayern = new javax.swing.JToggleButton();
        btnBenfica = new javax.swing.JToggleButton();
        btnDortmund = new javax.swing.JToggleButton();
        btnChelsea = new javax.swing.JToggleButton();
        btnJuventus = new javax.swing.JToggleButton();
        btnLiverpool = new javax.swing.JToggleButton();
        btnManCity = new javax.swing.JToggleButton();
        btnInter = new javax.swing.JToggleButton();
        btnManUnited = new javax.swing.JToggleButton();
        btnMilan = new javax.swing.JToggleButton();
        btnNapoli = new javax.swing.JToggleButton();
        btnPorto = new javax.swing.JToggleButton();
        btnPsg = new javax.swing.JToggleButton();
        btnRealMadrid = new javax.swing.JToggleButton();
        btnRoma = new javax.swing.JToggleButton();
        btnSporting = new javax.swing.JToggleButton();
        tbpAmerica = new javax.swing.JPanel();
        btnAtleticoNacional = new javax.swing.JToggleButton();
        btnBocaJuniors = new javax.swing.JToggleButton();
        btnBolivar = new javax.swing.JToggleButton();
        btnCerroPorteno = new javax.swing.JToggleButton();
        btnColoColo = new javax.swing.JToggleButton();
        btnEstudiantes = new javax.swing.JToggleButton();
        btnGuayaquill = new javax.swing.JToggleButton();
        btnIndependiente = new javax.swing.JToggleButton();
        btnJorge = new javax.swing.JToggleButton();
        btnLdu = new javax.swing.JToggleButton();
        btnNacional = new javax.swing.JToggleButton();
        btnIndValle = new javax.swing.JToggleButton();
        btnOlimpia = new javax.swing.JToggleButton();
        btnPenarol = new javax.swing.JToggleButton();
        btnRacing = new javax.swing.JToggleButton();
        btnRiverPlate = new javax.swing.JToggleButton();
        btnSportingCristal = new javax.swing.JToggleButton();
        btnTolima = new javax.swing.JToggleButton();
        btnUniversidadCatolica = new javax.swing.JToggleButton();
        btnUniverstiario = new javax.swing.JToggleButton();
        lblBRTS = new javax.swing.JLabel();
        lblWallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Área do Editor");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAnteriorLiga.setBackground(new java.awt.Color(0, 0, 0));
        btnAnteriorLiga.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnAnteriorLiga.setForeground(new java.awt.Color(255, 255, 255));
        btnAnteriorLiga.setText("<");
        btnAnteriorLiga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAnteriorLiga.setBorderPainted(false);
        btnAnteriorLiga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnteriorLiga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnteriorLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorLigaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnteriorLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 50, 150));

        btnProximoLiga.setBackground(new java.awt.Color(0, 0, 0));
        btnProximoLiga.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnProximoLiga.setForeground(new java.awt.Color(255, 255, 255));
        btnProximoLiga.setText(">");
        btnProximoLiga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnProximoLiga.setBorderPainted(false);
        btnProximoLiga.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProximoLiga.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProximoLiga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoLigaActionPerformed(evt);
            }
        });
        getContentPane().add(btnProximoLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 50, 50, 150));

        lblNomeLiga.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblNomeLiga.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeLiga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeLiga.setText(ListaEquipe.listaLiga().get(0).getNome().toUpperCase());
        getContentPane().add(lblNomeLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, 250, 40));

        lblLiga.setBackground(new java.awt.Color(255, 255, 255));
        lblLiga.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLiga.setIcon(ListaEquipe.listaLiga().get(0).getLogo());
        lblLiga.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        getContentPane().add(lblLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 150, 150));

        panFundoLiga.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(panFundoLiga, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, 250, 190));

        cbxChave.setBackground(new java.awt.Color(255, 255, 255));
        cbxChave.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        cbxChave.setForeground(new java.awt.Color(0, 0, 0));
        cbxChave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chaveamento Aleatório", "Chavemento em série" }));
        cbxChave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        cbxChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxChaveActionPerformed(evt);
            }
        });
        getContentPane().add(cbxChave, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 250, 40));

        lblEquipe.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblEquipe.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lblEquipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 410, 50));

        lblLimite.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        lblLimite.setForeground(new java.awt.Color(255, 255, 255));
        lblLimite.setText("Times selecionados: " + limite);
        getContentPane().add(lblLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 250, 40));

        btnAnteriorTrofeu.setBackground(new java.awt.Color(0, 0, 0));
        btnAnteriorTrofeu.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnAnteriorTrofeu.setForeground(new java.awt.Color(255, 255, 255));
        btnAnteriorTrofeu.setText("<");
        btnAnteriorTrofeu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnAnteriorTrofeu.setBorderPainted(false);
        btnAnteriorTrofeu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAnteriorTrofeu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAnteriorTrofeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorTrofeuActionPerformed(evt);
            }
        });
        getContentPane().add(btnAnteriorTrofeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 50, 150));

        btnProximoTrofeu.setBackground(new java.awt.Color(0, 0, 0));
        btnProximoTrofeu.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        btnProximoTrofeu.setForeground(new java.awt.Color(255, 255, 255));
        btnProximoTrofeu.setText(">");
        btnProximoTrofeu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        btnProximoTrofeu.setBorderPainted(false);
        btnProximoTrofeu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnProximoTrofeu.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProximoTrofeu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoTrofeuActionPerformed(evt);
            }
        });
        getContentPane().add(btnProximoTrofeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 50, 150));

        lblTrofeu.setBackground(new java.awt.Color(255, 255, 255));
        lblTrofeu.setIcon(ListaEquipe.listaTrofeu().get(0).getLogo());
        lblTrofeu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        getContentPane().add(lblTrofeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 370, 150, 150));

        panFundoTrofeu.setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().add(panFundoTrofeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 370, 250, 150));

        btnAleatorio.setBackground(new java.awt.Color(255, 255, 255));
        btnAleatorio.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnAleatorio.setForeground(new java.awt.Color(0, 0, 0));
        btnAleatorio.setText("Randomizar definições");
        btnAleatorio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAleatorioActionPerformed(evt);
            }
        });
        getContentPane().add(btnAleatorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 540, 250, 40));

        btnCriar.setBackground(new java.awt.Color(255, 255, 255));
        btnCriar.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        btnCriar.setForeground(new java.awt.Color(0, 0, 0));
        btnCriar.setText("Criar Campeonato");
        btnCriar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        btnCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCriar, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 300, 250, 60));

        tbpChefe.setBackground(new java.awt.Color(0, 0, 0));
        tbpChefe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbpChefe.setForeground(new java.awt.Color(255, 255, 255));
        tbpChefe.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        tbpBrasil.setBackground(new java.awt.Color(0, 0, 0));
        tbpBrasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbpBrasil.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAthleticoPR.setBackground(new java.awt.Color(0, 0, 0));
        btnAthleticoPR.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\AthleticoPR.png"));
        btnAthleticoPR.setContentAreaFilled(false);
        btnAthleticoPR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAthleticoPR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAthleticoPRActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnAthleticoPR, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 85, 85));

        btnAtleticoMG.setBackground(new java.awt.Color(0, 0, 0));
        btnAtleticoMG.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\AtleticoMG.png"));
        btnAtleticoMG.setContentAreaFilled(false);
        btnAtleticoMG.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtleticoMG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtleticoMGActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnAtleticoMG, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 6, 85, 85));

        btnBahia.setBackground(new java.awt.Color(0, 0, 0));
        btnBahia.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Bahia.png"));
        btnBahia.setContentAreaFilled(false);
        btnBahia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBahia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBahiaActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnBahia, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 6, 85, 85));

        btnBotafogo.setBackground(new java.awt.Color(0, 0, 0));
        btnBotafogo.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Botafogo.png"));
        btnBotafogo.setContentAreaFilled(false);
        btnBotafogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBotafogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBotafogoActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnBotafogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 6, 85, 85));

        btnCeara.setBackground(new java.awt.Color(0, 0, 0));
        btnCeara.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Ceara.png"));
        btnCeara.setContentAreaFilled(false);
        btnCeara.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCeara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCearaActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnCeara, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 85, 85));

        btnCorinthians.setBackground(new java.awt.Color(0, 0, 0));
        btnCorinthians.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Corinthians.png"));
        btnCorinthians.setContentAreaFilled(false);
        btnCorinthians.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCorinthians.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCorinthiansActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnCorinthians, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 103, 85, 85));

        btnCoritiba.setBackground(new java.awt.Color(0, 0, 0));
        btnCoritiba.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Coritiba.png"));
        btnCoritiba.setContentAreaFilled(false);
        btnCoritiba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCoritiba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCoritibaActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnCoritiba, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 103, 85, 85));

        btnCruzeiro.setBackground(new java.awt.Color(0, 0, 0));
        btnCruzeiro.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Cruzeiro.png"));
        btnCruzeiro.setContentAreaFilled(false);
        btnCruzeiro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCruzeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCruzeiroActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnCruzeiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 103, 85, 85));

        btnFlamengo.setBackground(new java.awt.Color(0, 0, 0));
        btnFlamengo.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Flamengo.png"));
        btnFlamengo.setContentAreaFilled(false);
        btnFlamengo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFlamengo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFlamengoActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnFlamengo, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 200, 85, 85));

        btnFluminense.setBackground(new java.awt.Color(0, 0, 0));
        btnFluminense.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Fluminense.png"));
        btnFluminense.setContentAreaFilled(false);
        btnFluminense.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFluminense.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFluminenseActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnFluminense, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 85, 85));

        btnFortaleza.setBackground(new java.awt.Color(0, 0, 0));
        btnFortaleza.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Fortaleza.png"));
        btnFortaleza.setContentAreaFilled(false);
        btnFortaleza.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFortaleza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFortalezaActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnFortaleza, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 200, 85, 85));

        btnCuiaba.setBackground(new java.awt.Color(0, 0, 0));
        btnCuiaba.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Cuiaba.png"));
        btnCuiaba.setContentAreaFilled(false);
        btnCuiaba.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCuiaba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuiabaActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnCuiaba, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 85, 85));

        btnGremio.setBackground(new java.awt.Color(0, 0, 0));
        btnGremio.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Gremio.png"));
        btnGremio.setContentAreaFilled(false);
        btnGremio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGremio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGremioActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnGremio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 297, 85, 85));

        btnInternacional.setBackground(new java.awt.Color(0, 0, 0));
        btnInternacional.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Internacional.png"));
        btnInternacional.setContentAreaFilled(false);
        btnInternacional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInternacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInternacionalActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnInternacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 297, 85, 85));

        btnPalmeiras.setBackground(new java.awt.Color(0, 0, 0));
        btnPalmeiras.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Palmeiras.png"));
        btnPalmeiras.setContentAreaFilled(false);
        btnPalmeiras.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPalmeiras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPalmeirasActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnPalmeiras, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 297, 85, 85));

        btnPaysandu.setBackground(new java.awt.Color(0, 0, 0));
        btnPaysandu.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Paysandu.png"));
        btnPaysandu.setContentAreaFilled(false);
        btnPaysandu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPaysandu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaysanduActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnPaysandu, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 297, 85, 85));

        btnRemo.setBackground(new java.awt.Color(0, 0, 0));
        btnRemo.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Remo.png"));
        btnRemo.setContentAreaFilled(false);
        btnRemo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRemo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnRemo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 394, 85, 85));

        btnSantos.setBackground(new java.awt.Color(0, 0, 0));
        btnSantos.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Santos.png"));
        btnSantos.setContentAreaFilled(false);
        btnSantos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSantos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSantosActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnSantos, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 394, 85, 85));

        btnSaoPaulo.setBackground(new java.awt.Color(0, 0, 0));
        btnSaoPaulo.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\SaoPaulo.png"));
        btnSaoPaulo.setContentAreaFilled(false);
        btnSaoPaulo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaoPaulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaoPauloActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnSaoPaulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 394, 85, 85));

        btnVasco.setBackground(new java.awt.Color(0, 0, 0));
        btnVasco.setIcon(new ImageIcon("src\\imagens\\logos\\brasil\\Vasco.png"));
        btnVasco.setContentAreaFilled(false);
        btnVasco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVasco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVascoActionPerformed(evt);
            }
        });
        tbpBrasil.add(btnVasco, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 394, 85, 85));

        tbpChefe.addTab("BRASIL", tbpBrasil);

        tbpEuropa.setBackground(new java.awt.Color(0, 0, 0));
        tbpEuropa.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbpEuropa.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnArsenal.setBackground(new java.awt.Color(0, 0, 0));
        btnArsenal.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Arsenal.png"));
        btnArsenal.setContentAreaFilled(false);
        btnArsenal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnArsenal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArsenalActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnArsenal, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 85, 85));

        btnAtleti.setBackground(new java.awt.Color(0, 0, 0));
        btnAtleti.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Atleti.png"));
        btnAtleti.setContentAreaFilled(false);
        btnAtleti.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtleti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtletiActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnAtleti, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 6, 85, 85));

        btnBarcelona.setBackground(new java.awt.Color(0, 0, 0));
        btnBarcelona.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Barcelona.png"));
        btnBarcelona.setContentAreaFilled(false);
        btnBarcelona.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBarcelona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBarcelonaActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnBarcelona, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 6, 85, 85));

        btnLeverkusen.setBackground(new java.awt.Color(0, 0, 0));
        btnLeverkusen.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Leverkusen.png"));
        btnLeverkusen.setContentAreaFilled(false);
        btnLeverkusen.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLeverkusen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLeverkusenActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnLeverkusen, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 6, 85, 85));

        btnBayern.setBackground(new java.awt.Color(0, 0, 0));
        btnBayern.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Bayern.png"));
        btnBayern.setContentAreaFilled(false);
        btnBayern.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBayern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBayernActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnBayern, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 85, 85));

        btnBenfica.setBackground(new java.awt.Color(0, 0, 0));
        btnBenfica.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Benfica.png"));
        btnBenfica.setContentAreaFilled(false);
        btnBenfica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBenfica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBenficaActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnBenfica, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 103, 85, 85));

        btnDortmund.setBackground(new java.awt.Color(0, 0, 0));
        btnDortmund.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Dortmund.png"));
        btnDortmund.setContentAreaFilled(false);
        btnDortmund.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDortmund.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDortmundActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnDortmund, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 103, 85, 85));

        btnChelsea.setBackground(new java.awt.Color(0, 0, 0));
        btnChelsea.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Chelsea.png"));
        btnChelsea.setContentAreaFilled(false);
        btnChelsea.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnChelsea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChelseaActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnChelsea, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 103, 85, 85));

        btnJuventus.setBackground(new java.awt.Color(0, 0, 0));
        btnJuventus.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Juventus.png"));
        btnJuventus.setContentAreaFilled(false);
        btnJuventus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJuventus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJuventusActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnJuventus, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 200, 85, 85));

        btnLiverpool.setBackground(new java.awt.Color(0, 0, 0));
        btnLiverpool.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Liverpool.png"));
        btnLiverpool.setContentAreaFilled(false);
        btnLiverpool.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLiverpool.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLiverpoolActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnLiverpool, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 85, 85));

        btnManCity.setBackground(new java.awt.Color(0, 0, 0));
        btnManCity.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\ManchesterCity.png"));
        btnManCity.setContentAreaFilled(false);
        btnManCity.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManCityActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnManCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 200, 85, 85));

        btnInter.setBackground(new java.awt.Color(0, 0, 0));
        btnInter.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Inter.png"));
        btnInter.setContentAreaFilled(false);
        btnInter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInterActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnInter, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 85, 85));

        btnManUnited.setBackground(new java.awt.Color(0, 0, 0));
        btnManUnited.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\ManchesterUnited.png"));
        btnManUnited.setContentAreaFilled(false);
        btnManUnited.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnManUnited.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManUnitedActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnManUnited, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 297, 85, 85));

        btnMilan.setBackground(new java.awt.Color(0, 0, 0));
        btnMilan.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Milan.png"));
        btnMilan.setContentAreaFilled(false);
        btnMilan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMilan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMilanActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnMilan, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 297, 85, 85));

        btnNapoli.setBackground(new java.awt.Color(0, 0, 0));
        btnNapoli.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Napoli.png"));
        btnNapoli.setContentAreaFilled(false);
        btnNapoli.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNapoli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNapoliActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnNapoli, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 297, 85, 85));

        btnPorto.setBackground(new java.awt.Color(0, 0, 0));
        btnPorto.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Porto.png"));
        btnPorto.setContentAreaFilled(false);
        btnPorto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPorto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPortoActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnPorto, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 297, 85, 85));

        btnPsg.setBackground(new java.awt.Color(0, 0, 0));
        btnPsg.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Psg.png"));
        btnPsg.setContentAreaFilled(false);
        btnPsg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPsgActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnPsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 394, 85, 85));

        btnRealMadrid.setBackground(new java.awt.Color(0, 0, 0));
        btnRealMadrid.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\RealMadrid.png"));
        btnRealMadrid.setContentAreaFilled(false);
        btnRealMadrid.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRealMadrid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRealMadridActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnRealMadrid, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 394, 85, 85));

        btnRoma.setBackground(new java.awt.Color(0, 0, 0));
        btnRoma.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Roma.png"));
        btnRoma.setContentAreaFilled(false);
        btnRoma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRomaActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnRoma, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 394, 85, 85));

        btnSporting.setBackground(new java.awt.Color(0, 0, 0));
        btnSporting.setIcon(new ImageIcon("src\\imagens\\logos\\europa\\Sporting.png"));
        btnSporting.setContentAreaFilled(false);
        btnSporting.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSporting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportingActionPerformed(evt);
            }
        });
        tbpEuropa.add(btnSporting, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 394, 85, 85));

        tbpChefe.addTab("EUROPA", tbpEuropa);

        tbpAmerica.setBackground(new java.awt.Color(0, 0, 0));
        tbpAmerica.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbpAmerica.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAtleticoNacional.setBackground(new java.awt.Color(0, 0, 0));
        btnAtleticoNacional.setIcon(new ImageIcon("src\\imagens\\logos\\america\\AtleticoNacional.png"));
        btnAtleticoNacional.setContentAreaFilled(false);
        btnAtleticoNacional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAtleticoNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtleticoNacionalActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnAtleticoNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 85, 85));

        btnBocaJuniors.setBackground(new java.awt.Color(0, 0, 0));
        btnBocaJuniors.setIcon(new ImageIcon("src\\imagens\\logos\\america\\BocaJuniors.png"));
        btnBocaJuniors.setContentAreaFilled(false);
        btnBocaJuniors.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBocaJuniors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBocaJuniorsActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnBocaJuniors, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 6, 85, 85));

        btnBolivar.setBackground(new java.awt.Color(0, 0, 0));
        btnBolivar.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Bolivar.png"));
        btnBolivar.setContentAreaFilled(false);
        btnBolivar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBolivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBolivarActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnBolivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 6, 85, 85));

        btnCerroPorteno.setBackground(new java.awt.Color(0, 0, 0));
        btnCerroPorteno.setIcon(new ImageIcon("src\\imagens\\logos\\america\\CerroPorteno.png"));
        btnCerroPorteno.setContentAreaFilled(false);
        btnCerroPorteno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerroPorteno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerroPortenoActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnCerroPorteno, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 6, 85, 85));

        btnColoColo.setBackground(new java.awt.Color(0, 0, 0));
        btnColoColo.setIcon(new ImageIcon("src\\imagens\\logos\\america\\ColoColo.png"));
        btnColoColo.setContentAreaFilled(false);
        btnColoColo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnColoColo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColoColoActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnColoColo, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 103, 85, 85));

        btnEstudiantes.setBackground(new java.awt.Color(0, 0, 0));
        btnEstudiantes.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Estudiantes.png"));
        btnEstudiantes.setContentAreaFilled(false);
        btnEstudiantes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstudiantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstudiantesActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 103, 85, 85));

        btnGuayaquill.setBackground(new java.awt.Color(0, 0, 0));
        btnGuayaquill.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Guayaquill.png"));
        btnGuayaquill.setContentAreaFilled(false);
        btnGuayaquill.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGuayaquill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuayaquillActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnGuayaquill, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 103, 85, 85));

        btnIndependiente.setBackground(new java.awt.Color(0, 0, 0));
        btnIndependiente.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Independiente.png"));
        btnIndependiente.setContentAreaFilled(false);
        btnIndependiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIndependiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndependienteActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnIndependiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 103, 85, 85));

        btnJorge.setBackground(new java.awt.Color(0, 0, 0));
        btnJorge.setIcon(new ImageIcon("src\\imagens\\logos\\america\\JorgeWilstermann.png"));
        btnJorge.setContentAreaFilled(false);
        btnJorge.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnJorge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJorgeActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnJorge, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 200, 85, 85));

        btnLdu.setBackground(new java.awt.Color(0, 0, 0));
        btnLdu.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Ldu.png"));
        btnLdu.setContentAreaFilled(false);
        btnLdu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLdu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLduActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnLdu, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 85, 85));

        btnNacional.setBackground(new java.awt.Color(0, 0, 0));
        btnNacional.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Nacional.png"));
        btnNacional.setContentAreaFilled(false);
        btnNacional.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnNacional.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNacionalActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnNacional, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 200, 85, 85));

        btnIndValle.setBackground(new java.awt.Color(0, 0, 0));
        btnIndValle.setIcon(new ImageIcon("src\\imagens\\logos\\america\\IndValle.png"));
        btnIndValle.setContentAreaFilled(false);
        btnIndValle.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnIndValle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIndValleActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnIndValle, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 200, 85, 85));

        btnOlimpia.setBackground(new java.awt.Color(0, 0, 0));
        btnOlimpia.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Olimpia.png"));
        btnOlimpia.setContentAreaFilled(false);
        btnOlimpia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOlimpia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOlimpiaActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnOlimpia, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 297, 85, 85));

        btnPenarol.setBackground(new java.awt.Color(0, 0, 0));
        btnPenarol.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Penarol.png"));
        btnPenarol.setContentAreaFilled(false);
        btnPenarol.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnPenarol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPenarolActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnPenarol, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 297, 85, 85));

        btnRacing.setBackground(new java.awt.Color(0, 0, 0));
        btnRacing.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Racing.png"));
        btnRacing.setContentAreaFilled(false);
        btnRacing.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRacing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRacingActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnRacing, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 297, 85, 85));

        btnRiverPlate.setBackground(new java.awt.Color(0, 0, 0));
        btnRiverPlate.setIcon(new ImageIcon("src\\imagens\\logos\\america\\RiverPlate.png"));
        btnRiverPlate.setContentAreaFilled(false);
        btnRiverPlate.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRiverPlate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiverPlateActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnRiverPlate, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 297, 85, 85));

        btnSportingCristal.setBackground(new java.awt.Color(0, 0, 0));
        btnSportingCristal.setIcon(new ImageIcon("src\\imagens\\logos\\america\\SportingCristal.png"));
        btnSportingCristal.setContentAreaFilled(false);
        btnSportingCristal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSportingCristal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSportingCristalActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnSportingCristal, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 394, 85, 85));

        btnTolima.setBackground(new java.awt.Color(0, 0, 0));
        btnTolima.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Tolima.png"));
        btnTolima.setContentAreaFilled(false);
        btnTolima.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTolima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTolimaActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnTolima, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 394, 85, 85));

        btnUniversidadCatolica.setBackground(new java.awt.Color(0, 0, 0));
        btnUniversidadCatolica.setIcon(new ImageIcon("src\\imagens\\logos\\america\\UniversidadCatolica.png"));
        btnUniversidadCatolica.setContentAreaFilled(false);
        btnUniversidadCatolica.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUniversidadCatolica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniversidadCatolicaActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnUniversidadCatolica, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 394, 85, 85));

        btnUniverstiario.setBackground(new java.awt.Color(0, 0, 0));
        btnUniverstiario.setIcon(new ImageIcon("src\\imagens\\logos\\america\\Universitario.png"));
        btnUniverstiario.setContentAreaFilled(false);
        btnUniverstiario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnUniverstiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUniverstiarioActionPerformed(evt);
            }
        });
        tbpAmerica.add(btnUniverstiario, new org.netbeans.lib.awtextra.AbsoluteConstraints(297, 394, 85, 85));

        tbpChefe.addTab("AMÉRICA", tbpAmerica);

        getContentPane().add(tbpChefe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 400, 500));
        tbpChefe.setUI(new javax.swing.plaf.basic.BasicTabbedPaneUI() {
            @Override
            protected int calculateTabAreaHeight(int tabPlacement, int runCount, int maxTabHeight) {
                return 0; // Altura das abas definida para 0, tornando-as invisíveis
            }
        });

        lblBRTS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logos/brts.png"))); // NOI18N
        getContentPane().add(lblBRTS, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 0, 50, 50));

        lblWallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/back-principal.png"))); // NOI18N
        getContentPane().add(lblWallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 600));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAthleticoPRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAthleticoPRActionPerformed
        botao(btnAthleticoPR);
    }//GEN-LAST:event_btnAthleticoPRActionPerformed

    private void btnAtleticoMGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtleticoMGActionPerformed
        botao(btnAtleticoMG);
    }//GEN-LAST:event_btnAtleticoMGActionPerformed

    private void btnBahiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBahiaActionPerformed
        botao(btnBahia);
    }//GEN-LAST:event_btnBahiaActionPerformed

    private void btnBotafogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBotafogoActionPerformed
        botao(btnBotafogo);
    }//GEN-LAST:event_btnBotafogoActionPerformed

    private void btnCearaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCearaActionPerformed
       botao(btnCeara);
    }//GEN-LAST:event_btnCearaActionPerformed

    private void btnCorinthiansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCorinthiansActionPerformed
        botao(btnCorinthians);
    }//GEN-LAST:event_btnCorinthiansActionPerformed

    private void btnCoritibaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCoritibaActionPerformed
        botao(btnCoritiba);
    }//GEN-LAST:event_btnCoritibaActionPerformed

    private void btnCruzeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCruzeiroActionPerformed
        botao(btnCruzeiro);
    }//GEN-LAST:event_btnCruzeiroActionPerformed

    private void btnFlamengoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFlamengoActionPerformed
        botao(btnFlamengo);
    }//GEN-LAST:event_btnFlamengoActionPerformed

    private void btnFluminenseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFluminenseActionPerformed
        botao(btnFluminense);
    }//GEN-LAST:event_btnFluminenseActionPerformed

    private void btnFortalezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFortalezaActionPerformed
        botao(btnFortaleza);
    }//GEN-LAST:event_btnFortalezaActionPerformed

    private void btnCuiabaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuiabaActionPerformed
       botao(btnCuiaba);
    }//GEN-LAST:event_btnCuiabaActionPerformed

    private void btnGremioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGremioActionPerformed
        botao(btnGremio);
    }//GEN-LAST:event_btnGremioActionPerformed

    private void btnInternacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInternacionalActionPerformed
        botao(btnInternacional);
    }//GEN-LAST:event_btnInternacionalActionPerformed

    private void btnPalmeirasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPalmeirasActionPerformed
        botao(btnPalmeiras);
    }//GEN-LAST:event_btnPalmeirasActionPerformed

    private void btnPaysanduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaysanduActionPerformed
        botao(btnPaysandu);
    }//GEN-LAST:event_btnPaysanduActionPerformed

    private void btnRemoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoActionPerformed
        botao(btnRemo);
    }//GEN-LAST:event_btnRemoActionPerformed

    private void btnSantosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSantosActionPerformed
        botao(btnSantos);
    }//GEN-LAST:event_btnSantosActionPerformed

    private void btnSaoPauloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaoPauloActionPerformed
        botao(btnSaoPaulo);
    }//GEN-LAST:event_btnSaoPauloActionPerformed

    private void btnVascoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVascoActionPerformed
        botao(btnVasco);
    }//GEN-LAST:event_btnVascoActionPerformed

    private void btnArsenalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArsenalActionPerformed
        botao(btnArsenal);
    }//GEN-LAST:event_btnArsenalActionPerformed

    private void btnAtletiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtletiActionPerformed
        botao(btnAtleti);
    }//GEN-LAST:event_btnAtletiActionPerformed

    private void btnBarcelonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBarcelonaActionPerformed
        botao(btnBarcelona);
    }//GEN-LAST:event_btnBarcelonaActionPerformed

    private void btnLeverkusenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLeverkusenActionPerformed
        botao(btnLeverkusen);
    }//GEN-LAST:event_btnLeverkusenActionPerformed

    private void btnBayernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBayernActionPerformed
        botao(btnBayern);
    }//GEN-LAST:event_btnBayernActionPerformed

    private void btnBenficaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBenficaActionPerformed
        botao(btnBenfica);
    }//GEN-LAST:event_btnBenficaActionPerformed

    private void btnDortmundActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDortmundActionPerformed
        botao(btnDortmund);
    }//GEN-LAST:event_btnDortmundActionPerformed

    private void btnChelseaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChelseaActionPerformed
        botao(btnChelsea);
    }//GEN-LAST:event_btnChelseaActionPerformed

    private void btnJuventusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJuventusActionPerformed
        botao(btnJuventus);
    }//GEN-LAST:event_btnJuventusActionPerformed

    private void btnLiverpoolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLiverpoolActionPerformed
        botao(btnLiverpool);
    }//GEN-LAST:event_btnLiverpoolActionPerformed

    private void btnManCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManCityActionPerformed
        botao(btnManCity);
    }//GEN-LAST:event_btnManCityActionPerformed

    private void btnInterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInterActionPerformed
        botao(btnInter);
    }//GEN-LAST:event_btnInterActionPerformed

    private void btnManUnitedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManUnitedActionPerformed
        botao(btnManUnited);
    }//GEN-LAST:event_btnManUnitedActionPerformed

    private void btnMilanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMilanActionPerformed
        botao(btnMilan);
    }//GEN-LAST:event_btnMilanActionPerformed

    private void btnNapoliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNapoliActionPerformed
        botao(btnNapoli);
    }//GEN-LAST:event_btnNapoliActionPerformed

    private void btnPortoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPortoActionPerformed
        botao(btnPorto);
    }//GEN-LAST:event_btnPortoActionPerformed

    private void btnPsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPsgActionPerformed
        botao(btnPsg);
    }//GEN-LAST:event_btnPsgActionPerformed

    private void btnRealMadridActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRealMadridActionPerformed
        botao(btnRealMadrid);
    }//GEN-LAST:event_btnRealMadridActionPerformed

    private void btnRomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRomaActionPerformed
        botao(btnRoma);
    }//GEN-LAST:event_btnRomaActionPerformed

    private void btnSportingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSportingActionPerformed
        botao(btnSporting);
    }//GEN-LAST:event_btnSportingActionPerformed

    private void btnAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAleatorioActionPerformed
        lista = ListaEquipe.listaEquipe();
        Collections.shuffle(lista);
        
        for(int i = lista.size()-1 ; i >= 8 ; i--)
        {
            lista.remove(i);
        }
        Random random = new Random();
        trofeu = random.nextInt(3);
        
         lista.add(ListaEquipe.listaTrofeu().get(trofeu));
            
        retorno();
        dispose();
    }//GEN-LAST:event_btnAleatorioActionPerformed

    private void cbxChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxChaveActionPerformed

    private void btnCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarActionPerformed
        if(limite == 8)
        {
            if(cbxChave.getSelectedItem().equals("Chaveamento Aleatório"))
            {
                Collections.shuffle(lista);
            }
            
            lista.add(ListaEquipe.listaTrofeu().get(trofeu));
            
            retorno();
            dispose();
        }
        else
        {
            JOptionPane.showMessageDialog(null, "É necessário ter 8 equipes.");
        }
    }//GEN-LAST:event_btnCriarActionPerformed

    private void btnProximoTrofeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoTrofeuActionPerformed
        switch (trofeu) {
            case 0: trofeu = 1 ; break;
            case 1: trofeu = 2 ; break;
            case 2: trofeu = 3 ; break;
            case 3: trofeu = 4 ; break;
            case 4: trofeu = 5 ; break;
            case 5: trofeu = 6 ; break;
            case 6: trofeu = 0 ; break;
            default : throw new AssertionError();
        }
        lblTrofeu.setIcon(ListaEquipe.listaTrofeu().get(trofeu).getLogo());
    }//GEN-LAST:event_btnProximoTrofeuActionPerformed

    private void btnAnteriorTrofeuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorTrofeuActionPerformed
        switch (trofeu) {
            case 0: trofeu = 6 ; break;
            case 1: trofeu = 0 ; break;
            case 2: trofeu = 1 ; break;
            case 3: trofeu = 2 ; break;
            case 4: trofeu = 3 ; break;
            case 5: trofeu = 4 ; break;
            case 6: trofeu = 5 ; break;
            default : throw new AssertionError();
        }
        lblTrofeu.setIcon(ListaEquipe.listaTrofeu().get(trofeu).getLogo());
    }//GEN-LAST:event_btnAnteriorTrofeuActionPerformed

    private void btnAtleticoNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtleticoNacionalActionPerformed
        botao(btnAtleticoNacional);
    }//GEN-LAST:event_btnAtleticoNacionalActionPerformed

    private void btnBocaJuniorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBocaJuniorsActionPerformed
        botao(btnBocaJuniors);
    }//GEN-LAST:event_btnBocaJuniorsActionPerformed

    private void btnBolivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBolivarActionPerformed
        botao(btnBolivar);
    }//GEN-LAST:event_btnBolivarActionPerformed

    private void btnCerroPortenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerroPortenoActionPerformed
        botao(btnCerroPorteno);
    }//GEN-LAST:event_btnCerroPortenoActionPerformed

    private void btnColoColoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColoColoActionPerformed
        botao(btnColoColo);
    }//GEN-LAST:event_btnColoColoActionPerformed

    private void btnEstudiantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstudiantesActionPerformed
        botao(btnEstudiantes);
    }//GEN-LAST:event_btnEstudiantesActionPerformed

    private void btnGuayaquillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuayaquillActionPerformed
        botao(btnGuayaquill);
    }//GEN-LAST:event_btnGuayaquillActionPerformed

    private void btnIndependienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndependienteActionPerformed
        botao(btnIndependiente);
    }//GEN-LAST:event_btnIndependienteActionPerformed

    private void btnJorgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJorgeActionPerformed
        botao(btnJorge);
    }//GEN-LAST:event_btnJorgeActionPerformed

    private void btnLduActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLduActionPerformed
        botao(btnLdu);
    }//GEN-LAST:event_btnLduActionPerformed

    private void btnNacionalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNacionalActionPerformed
        botao(btnNacional);
    }//GEN-LAST:event_btnNacionalActionPerformed

    private void btnIndValleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIndValleActionPerformed
        botao(btnIndValle);
    }//GEN-LAST:event_btnIndValleActionPerformed

    private void btnOlimpiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOlimpiaActionPerformed
        botao(btnOlimpia);
    }//GEN-LAST:event_btnOlimpiaActionPerformed

    private void btnPenarolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPenarolActionPerformed
        botao(btnPenarol);
    }//GEN-LAST:event_btnPenarolActionPerformed

    private void btnRacingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRacingActionPerformed
        botao(btnRacing);
    }//GEN-LAST:event_btnRacingActionPerformed

    private void btnRiverPlateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiverPlateActionPerformed
        botao(btnRiverPlate);
    }//GEN-LAST:event_btnRiverPlateActionPerformed

    private void btnSportingCristalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSportingCristalActionPerformed
        botao(btnSportingCristal);
    }//GEN-LAST:event_btnSportingCristalActionPerformed

    private void btnTolimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTolimaActionPerformed
        botao(btnTolima);
    }//GEN-LAST:event_btnTolimaActionPerformed

    private void btnUniversidadCatolicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniversidadCatolicaActionPerformed
        botao(btnUniversidadCatolica);
    }//GEN-LAST:event_btnUniversidadCatolicaActionPerformed

    private void btnUniverstiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUniverstiarioActionPerformed
        botao(btnUniverstiario);
    }//GEN-LAST:event_btnUniverstiarioActionPerformed

    private void btnAnteriorLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorLigaActionPerformed
        switch (liga) {
            case 0: liga = 2 ; break;
            case 1: liga = 0 ; break;
            case 2: liga = 1 ; break;
            default : throw new AssertionError();
        }
        lblLiga.setIcon(ListaEquipe.listaLiga().get(liga).getLogo());
        tbpChefe.setSelectedIndex(liga);
        lblNomeLiga.setText(ListaEquipe.listaLiga().get(liga).getNome().toUpperCase());
    }//GEN-LAST:event_btnAnteriorLigaActionPerformed

    private void btnProximoLigaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoLigaActionPerformed
        switch (liga) {
            case 0: liga = 1 ; break;
            case 1: liga = 2 ; break;
            case 2: liga = 0 ; break;
            default : throw new AssertionError();
        }
        lblLiga.setIcon(ListaEquipe.listaLiga().get(liga).getLogo());
        tbpChefe.setSelectedIndex(liga);
        lblNomeLiga.setText(ListaEquipe.listaLiga().get(liga).getNome().toUpperCase());
    }//GEN-LAST:event_btnProximoLigaActionPerformed

    public List<Equipe> retorno()
    {
        return lista;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEquipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEquipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEquipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEquipes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frmEquipes dialog = new frmEquipes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAleatorio;
    private javax.swing.JButton btnAnteriorLiga;
    private javax.swing.JButton btnAnteriorTrofeu;
    private javax.swing.JToggleButton btnArsenal;
    private javax.swing.JToggleButton btnAthleticoPR;
    private javax.swing.JToggleButton btnAtleti;
    private javax.swing.JToggleButton btnAtleticoMG;
    private javax.swing.JToggleButton btnAtleticoNacional;
    private javax.swing.JToggleButton btnBahia;
    private javax.swing.JToggleButton btnBarcelona;
    private javax.swing.JToggleButton btnBayern;
    private javax.swing.JToggleButton btnBenfica;
    private javax.swing.JToggleButton btnBocaJuniors;
    private javax.swing.JToggleButton btnBolivar;
    private javax.swing.JToggleButton btnBotafogo;
    private javax.swing.JToggleButton btnCeara;
    private javax.swing.JToggleButton btnCerroPorteno;
    private javax.swing.JToggleButton btnChelsea;
    private javax.swing.JToggleButton btnColoColo;
    private javax.swing.JToggleButton btnCorinthians;
    private javax.swing.JToggleButton btnCoritiba;
    private javax.swing.JButton btnCriar;
    private javax.swing.JToggleButton btnCruzeiro;
    private javax.swing.JToggleButton btnCuiaba;
    private javax.swing.JToggleButton btnDortmund;
    private javax.swing.JToggleButton btnEstudiantes;
    private javax.swing.JToggleButton btnFlamengo;
    private javax.swing.JToggleButton btnFluminense;
    private javax.swing.JToggleButton btnFortaleza;
    private javax.swing.JToggleButton btnGremio;
    private javax.swing.JToggleButton btnGuayaquill;
    private javax.swing.JToggleButton btnIndValle;
    private javax.swing.JToggleButton btnIndependiente;
    private javax.swing.JToggleButton btnInter;
    private javax.swing.JToggleButton btnInternacional;
    private javax.swing.JToggleButton btnJorge;
    private javax.swing.JToggleButton btnJuventus;
    private javax.swing.JToggleButton btnLdu;
    private javax.swing.JToggleButton btnLeverkusen;
    private javax.swing.JToggleButton btnLiverpool;
    private javax.swing.JToggleButton btnManCity;
    private javax.swing.JToggleButton btnManUnited;
    private javax.swing.JToggleButton btnMilan;
    private javax.swing.JToggleButton btnNacional;
    private javax.swing.JToggleButton btnNapoli;
    private javax.swing.JToggleButton btnOlimpia;
    private javax.swing.JToggleButton btnPalmeiras;
    private javax.swing.JToggleButton btnPaysandu;
    private javax.swing.JToggleButton btnPenarol;
    private javax.swing.JToggleButton btnPorto;
    private javax.swing.JButton btnProximoLiga;
    private javax.swing.JButton btnProximoTrofeu;
    private javax.swing.JToggleButton btnPsg;
    private javax.swing.JToggleButton btnRacing;
    private javax.swing.JToggleButton btnRealMadrid;
    private javax.swing.JToggleButton btnRemo;
    private javax.swing.JToggleButton btnRiverPlate;
    private javax.swing.JToggleButton btnRoma;
    private javax.swing.JToggleButton btnSantos;
    private javax.swing.JToggleButton btnSaoPaulo;
    private javax.swing.JToggleButton btnSporting;
    private javax.swing.JToggleButton btnSportingCristal;
    private javax.swing.JToggleButton btnTolima;
    private javax.swing.JToggleButton btnUniversidadCatolica;
    private javax.swing.JToggleButton btnUniverstiario;
    private javax.swing.JToggleButton btnVasco;
    private javax.swing.JComboBox<String> cbxChave;
    private javax.swing.JLabel lblBRTS;
    private javax.swing.JLabel lblEquipe;
    private javax.swing.JLabel lblLiga;
    private javax.swing.JLabel lblLimite;
    private javax.swing.JLabel lblNomeLiga;
    private javax.swing.JLabel lblTrofeu;
    private javax.swing.JLabel lblWallpaper;
    private javax.swing.JPanel panFundoLiga;
    private javax.swing.JPanel panFundoTrofeu;
    private javax.swing.JPanel tbpAmerica;
    private javax.swing.JPanel tbpBrasil;
    private javax.swing.JTabbedPane tbpChefe;
    private javax.swing.JPanel tbpEuropa;
    // End of variables declaration//GEN-END:variables
}
